---
title: "gProfiler Work - ABRF GBIRG"
author: "Charlie Whittaker"
date: "12/19/2020"
output: 
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Load libraries*

```{r, warning=FALSE,error=FALSE,message=FALSE}
library(openxlsx)
library(ggplot2)
library(tidyverse)
library(gprofiler2)
```

*Import Biological Concept Data*

```{r}
PPAR <- read.xlsx("../shared_data/KEGG_PPAR_SIGNALING_PATHWAY_withMouse.xlsx", colNames=TRUE, rowNames=FALSE)
E2F <- read.xlsx("../shared_data/HALLMARK_E2F_TARGETS.xlsx", colNames=TRUE, rowNames=FALSE)
TNF  <- read.xlsx("../shared_data/HALLMARK_TNFA_SIGNALING_VIA_NFKB.xlsx", colNames=TRUE, rowNames=FALSE)
MUSC <- read.xlsx("../shared_data/GO_SKELETAL_MUSCLE_CONTRACTION.xlsx", colNames=TRUE, rowNames=FALSE)
```

*Run gprofiler on Biological Concept sets*

```{r}
mmPPAR <- na.omit(PPAR$MGISym)
mmPPar.gostres <- gost(query = mmPPAR,organism = "mmusculus", 
                       sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"), 
                       domain_scope="annotated")

write.xlsx(mmPPar.gostres$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="mmPPAR.gprofiler.xlsx")
##
E2F.gostres <- gost(query = E2F$HALLMARK_E2F_TARGETS,organism = "hsapiens", 
                       sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"), 
                       domain_scope="annotated")

write.xlsx(E2F.gostres$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="E2F.gprofiler.xlsx")
##
TNF.gostres <- gost(query = TNF$HALLMARK_TNFA_SIGNALING_VIA_NFKB,organism = "hsapiens", 
                       sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"), 
                       domain_scope="annotated")

write.xlsx(TNF.gostres$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="TNF.gprofiler.xlsx")
##
MUSC.gostres <- gost(query = MUSC$GO_SKELETAL_MUSCLE_CONTRACTION,organism = "hsapiens", 
                       sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"), 
                       domain_scope="annotated")

write.xlsx(MUSC.gostres$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="MUSC.gprofiler.xlsx")
```

*Import experimental data*

```{r}
evc <- read.xlsx("../shared_data/EvC_data.xlsx", colNames=TRUE, rowNames=TRUE)
g1vrev <- read.xlsx("../shared_data/G1vRev_data.xlsx", colNames=TRUE, rowNames=TRUE)
hmp3avc <- read.xlsx("../shared_data/hpm3_AvC_data.xlsx", colNames=TRUE, rowNames=TRUE)
muscsvc <- read.xlsx("../shared_data/musc_SkeVHeart.xlsx", colNames=TRUE, rowNames=TRUE)
```

*Run gprofiler on experimental data*
```{r}
evc <- tibble::rownames_to_column(evc,"Gene")
evc.degs <- evc %>% filter(adp <= 0.05 & abs(logFC) >= 1)
evc.bkground <- evc %>% dplyr::select(c("Gene"))

#NOTE: I tested the run using the default annotated background compared to the gene list from the data file.
#There were more annotation hits with the pathway
#evc.gostres <- gost(query = evc.degs$Gene,organism = "mmusculus", 
#                sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"), 
#                domain_scope="annotated")

evc.gostres.bg <- gost(query = evc.degs$Gene,organism = "mmusculus", 
                sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"),
                significant = TRUE, correction_method ="g_SCS",
                custom_bg = evc.bkground$Gene, domain_scope="custom")

write.xlsx(evc.gostres.bg$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="evc.gprofiler.xlsx")
##
g1vrev <- tibble::rownames_to_column(g1vrev,"Gene")
g1vrev.degs <- g1vrev %>% filter(adp <= 0.05 & abs(logFC) >= 1)
g1vrev.bkground <- g1vrev %>% dplyr::select(c("Gene"))

g1vrev.gostres.bg <- gost(query = g1vrev.degs$Gene,organism = "hsapiens", 
                sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"),
                significant = TRUE, correction_method ="g_SCS",
                custom_bg = g1vrev.bkground$Gene, domain_scope="custom")

write.xlsx(g1vrev.gostres.bg$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="g1vrev.gprofiler.xlsx")

##
hmp3avc <- tibble::rownames_to_column(hmp3avc,"Gene")
hmp3avc.degs <- hmp3avc %>% filter(adp <= 0.05 & abs(logFC) >= 1)
hmp3avc.bkground <- hmp3avc %>% dplyr::select(c("Gene"))

hmp3avc.gostres.bg <- gost(query = hmp3avc.degs$Gene,organism = "hsapiens", 
                sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"),
                significant = TRUE, correction_method ="g_SCS",
                custom_bg = hmp3avc.bkground$Gene, domain_scope="custom")

write.xlsx(hmp3avc.gostres.bg$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="hmp3avc.gprofiler.xlsx")

##
muscsvc <- tibble::rownames_to_column(muscsvc,"Gene")
muscsvc.degs <- muscsvc %>% filter(adp <= 0.05 & abs(logFC) >= 1)
muscsvc.bkground <- muscsvc %>% dplyr::select(c("Gene"))

muscsvc.gostres.bg <- gost(query = muscsvc.degs$Gene,organism = "hsapiens", 
                sources = c("GO:BP", "GO:MF", "GO:CC", "KEGG", "REAC", "WP"),
                significant = TRUE, correction_method ="g_SCS",
                custom_bg = muscsvc.bkground$Gene, domain_scope="custom")

write.xlsx(muscsvc.gostres.bg$result %>% select(c("term_id", "term_name","source","p_value", "query_size", "intersection_size")), file="muscsvc.gprofiler.xlsx")

#p <- gostplot(mmPPar.gostres, capped = FALSE, interactive = FALSE)
#p
```

*alternative filtering

#```{r}
#g1vRev <- read.xlsx("../shared_data/GSE83647_G1vRev.xlsx", colNames=TRUE, rowNames=TRUE)
#g1vRev.path <- read.xlsx("../shared_data/HALLMARK_E2F_TARGETS.xlsx")
#
#g1vRev <- tibble::rownames_to_column(g1vRev,"Gene")
#g1vRev.degs <- g1vRev %>% filter(g1vRev$ape.G1.Rev.adp <= 0.05 
#                                 & MPG == "Yes" 
#                                 & abs(ape.G1.Rev.logFC) >= 0.58)
#```

## write session info*

```{r}
sessionInfo()
writeLines(capture.output(sessionInfo()), "sessionInfo.txt")
```