---
title: "Plotting Tests - ABRF GBIRG"
author: "Charlie Whittaker"
date: "12/16/2020"
output: 
  html_document: default
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*Load libraries*

```{r, warning=FALSE,error=FALSE,message=FALSE}
library(openxlsx)
library(ggplot2)
library(tidyverse)
library(ggpubr)
```

*Import GSEA Data*

```{r}
EvC.GSEA <- read.xlsx("../shared_data/EvC_GSEAv4_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
G1vRev.GSEA <- read.xlsx("../shared_data/G1vRev_GSEAv4_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
hpm3AvC.GSEA <- read.xlsx("../shared_data/hpm3_AvC_GSEAv4_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
MuscleSvC.GSEA <- read.xlsx("../shared_data/Muscle_SkeletalvsCardiac_GSEAv4_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
```

*GSEA Summary Plots_v2*

```{r, fig.width=10, fig.height=3}
evc.gsea.filt <- EvC.GSEA %>% filter(FDR <= 0.05) %>% filter(Collection %in% c("h","c2cgp","c2cp","c5bp", "c5mf", "c5cc"))
evc.gsea.filt <- tibble::rownames_to_column(evc.gsea.filt,"Name")
evc.gsea.nohit <- evc.gsea.filt %>% filter(Hit == "Other")
evc.gsea.hit <- evc.gsea.filt %>% filter(Hit == "Hit")
ec.gsea.plot <- ggplot() + geom_jitter(data=evc.gsea.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=evc.gsea.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("EvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

g1vrev.gsea.filt <- G1vRev.GSEA %>% filter(FDR <= 0.05) %>% filter(Collection %in% c("h","c2cgp","c2cp","c5bp", "c5mf", "c5cc"))
g1vrev.gsea.filt <- tibble::rownames_to_column(g1vrev.gsea.filt,"Name")
g1rev.gsea.nohit <- g1vrev.gsea.filt %>% filter(Hit == "Other")
g1rev.gsea.hit <- g1vrev.gsea.filt %>% filter(Hit == "Hit")
g1rev.gsea.plot <- ggplot() + geom_jitter(data=g1rev.gsea.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=g1rev.gsea.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("g1rev") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

hpm3AvC.gsea.filt <- hpm3AvC.GSEA %>% filter(FDR <= 0.05) %>% filter(Collection %in% c("h","c2cgp","c2cp","c5bp", "c5mf", "c5cc"))
hpm3AvC.gsea.filt <- tibble::rownames_to_column(hpm3AvC.gsea.filt,"Name")
ac.gsea.nohit <- hpm3AvC.gsea.filt %>% filter(Hit == "Other")
ac.gsea.hit <- hpm3AvC.gsea.filt %>% filter(Hit == "Hit")
ac.gsea.plot <- ggplot() + geom_jitter(data=ac.gsea.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=ac.gsea.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("hpm3.AvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()


MuscleSvC.gsea.filt <- MuscleSvC.GSEA %>% filter(FDR <= 0.05) %>% filter(Collection %in% c("h","c2cgp","c2cp","c5bp", "c5mf", "c5cc"))
MuscleSvC.gsea.filt <- tibble::rownames_to_column(MuscleSvC.gsea.filt,"Name")
sc.gsea.nohit <- MuscleSvC.gsea.filt %>% filter(Hit == "Other")
sc.gsea.hit <- MuscleSvC.gsea.filt %>% filter(Hit == "Hit")
sc.gsea.plot <- ggplot() + geom_jitter(data=sc.gsea.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=sc.gsea.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("MuscleSvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

ggarrange(ec.gsea.plot,g1rev.gsea.plot,ac.gsea.plot,sc.gsea.plot, legend = FALSE, ncol=4, nrow=1)
```

*Import DAVID Data*

```{r}
EvC.DAVID <- read.xlsx("../DAVID/evcDEGS.DAVID_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
G1vRev.DAVID <- read.xlsx("../DAVID/g1vRevDEGS.DAVID_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
hpm3AvC.DAVID <- read.xlsx("../DAVID/hpm3avc.DEGS.DAVID_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
MuscleSvC.DAVID <- read.xlsx("../DAVID/muscsvc.DEGS.DAVID_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
```

*DAVID Summary Plots_v2*

```{r, fig.width=10, fig.height=3}
evc.david.filt <- EvC.DAVID %>% filter(PValue <= 0.05)
evc.david.filt  <- tibble::rownames_to_column(evc.david.filt ,"Name")
evc.david.nohit <- evc.david.filt  %>% filter(Hit == "Other")
evc.david.hit <- evc.david.filt  %>% filter(Hit == "Hit")
ec.david.plot <- ggplot() + geom_jitter(data=evc.david.nohit, aes(x="Collection",y=PValue), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=evc.david.hit, aes(x="Collection",y=PValue), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("EvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

g1vrev.david.filt  <- G1vRev.DAVID %>% filter(PValue <= 0.05)
g1vrev.david.filt  <- tibble::rownames_to_column(g1vrev.david.filt ,"Name")
g1rev.david.nohit <- g1vrev.david.filt  %>% filter(Hit == "Other")
g1rev.david.hit <- g1vrev.david.filt  %>% filter(Hit == "Hit")
g1rev.david.plot <- ggplot() + geom_jitter(data=g1rev.david.nohit, aes(x="Collection",y=PValue), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=g1rev.david.hit, aes(x="Collection",y=PValue), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("g1rev") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

hpm3AvC.david.filt  <- hpm3AvC.DAVID %>% filter(PValue <= 0.05)
hpm3AvC.david.filt  <- tibble::rownames_to_column(hpm3AvC.david.filt ,"Name")
ac.david.nohit <- hpm3AvC.david.filt  %>% filter(Hit == "Other")
ac.david.hit <- hpm3AvC.david.filt  %>% filter(Hit == "Hit")
ac.david.plot <- ggplot() + geom_jitter(data=ac.david.nohit, aes(x="Collection",y=PValue), color="black", alpha=0.5, size=0.6, width=0.1) + geom_jitter(data=ac.david.hit, aes(x="Collection",y=PValue), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("hpm3.AvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()


MuscleSvC.david.filt  <- MuscleSvC.DAVID %>% filter(PValue <= 0.05)
MuscleSvC.david.filt  <- tibble::rownames_to_column(MuscleSvC.david.filt ,"Name")
sc.david.nohit <- MuscleSvC.david.filt  %>% filter(Hit == "Other")
sc.david.hit <- MuscleSvC.david.filt  %>% filter(Hit == "Hit")
sc.david.plot <- ggplot() + geom_jitter(data=sc.david.nohit, aes(x="Collection",y=PValue), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=sc.david.hit, aes(x="Collection",y=PValue), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("MuscleSvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

ggarrange(ec.david.plot,g1rev.david.plot,ac.david.plot,sc.david.plot, legend = FALSE, ncol=4, nrow=1)
```

*Import gProfiler Data*

```{r}
EvC.gprofiler <- read.xlsx("../g_profiler/evc.gprofiler_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
G1vRev.gprofiler <- read.xlsx("../g_profiler/g1vrev.gprofiler_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
hpm3AvC.gprofiler <- read.xlsx("../g_profiler/hpm3avc.gprofiler_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
MuscleSvC.gprofiler <- read.xlsx("../g_profiler/muscsvc.gprofiler_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
```

*Gprofiler Summary Plots_v2*

```{r, fig.width=10, fig.height=3}
evc.gpro.filt  <- EvC.gprofiler %>% filter(p_value <= 0.05)
evc.gpro.filt <- tibble::rownames_to_column(evc.gpro.filt,"Name")
evc.gpro.nohit <- evc.gpro.filt %>% filter(Hit == "Other")
evc.gpro.hit <- evc.gpro.filt %>% filter(Hit == "Hit")
ec.gpro.plot <- ggplot() + geom_jitter(data=evc.gpro.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=evc.gpro.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("EvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

g1vrev.gpro.filt <- G1vRev.gprofiler %>% filter(p_value <= 0.05)
g1vrev.gpro.filt <- tibble::rownames_to_column(g1vrev.gpro.filt,"Name")
g1rev.gpro.nohit <- g1vrev.gpro.filt %>% filter(Hit == "Other")
g1rev.gpro.hit <- g1vrev.gpro.filt %>% filter(Hit == "Hit")
g1rev.gpro.plot <- ggplot() + geom_jitter(data=g1rev.gpro.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=g1rev.gpro.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("g1rev") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

hpm3AvC.gpro.filt <- hpm3AvC.gprofiler %>% filter(p_value <= 0.05)
hpm3AvC.gpro.filt <- tibble::rownames_to_column(hpm3AvC.gpro.filt,"Name")
ac.gpro.nohit <- hpm3AvC.gpro.filt %>% filter(Hit == "Other")
ac.gpro.hit <- hpm3AvC.gpro.filt %>% filter(Hit == "Hit")
ac.gpro.plot <- ggplot() + geom_jitter(data=ac.gpro.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.5, size=0.6, width=0.1) + geom_jitter(data=ac.gpro.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("hpm3.AvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()


MuscleSvC.gpro.filt <- MuscleSvC.gprofiler %>% filter(p_value <= 0.05)
MuscleSvC.gpro.filt <- tibble::rownames_to_column(MuscleSvC.gpro.filt,"Name")
sc.gpro.nohit <- MuscleSvC.gpro.filt %>% filter(Hit == "Other")
sc.gpro.hit <- MuscleSvC.gpro.filt %>% filter(Hit == "Hit")
sc.gpro.plot <- ggplot() + geom_jitter(data=sc.gpro.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=sc.gpro.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("MuscleSvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

ggarrange(ec.gpro.plot,g1rev.gpro.plot,ac.gpro.plot,sc.gpro.plot, legend = FALSE, ncol=4, nrow=1)
```

*Import Metacore Data*

```{r}
EvC.metacore <- read.xlsx("../shared_data/EvC_metacore_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
G1vRev.metacore <- read.xlsx("../shared_data/G1vRev_metacore_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
hpm3AvC.metacore <- read.xlsx("../shared_data/hpm3_AvC_metacore_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
MuscleSvC.metacore <- read.xlsx("../shared_data/Muscle_SkeletalvsCardiac_metacore_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
```

*Metacore Summary Plots_v2*

```{r, fig.width=10, fig.height=3}
evc.mcore.filt <- EvC.metacore %>% filter(FDR <= 0.05)     
evc.mcore.filt <- tibble::rownames_to_column(evc.mcore.filt,"Name")
evc.mcore.nohit <- evc.mcore.filt %>% filter(Hit == "Other")
evc.mcore.hit <- evc.mcore.filt %>% filter(Hit == "Hit")
ec.mcore.plot <- ggplot() + geom_jitter(data=evc.mcore.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=evc.mcore.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("EvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()        

g1vrev.mcore.filt <- G1vRev.metacore %>% filter(FDR <= 0.05)     
g1vrev.mcore.filt <- tibble::rownames_to_column(g1vrev.mcore.filt,"Name")
g1rev.mcore.nohit <- g1vrev.mcore.filt %>% filter(Hit == "Other")
g1rev.mcore.hit <- g1vrev.mcore.filt %>% filter(Hit == "Hit")
g1rev.mcore.plot <- ggplot() + geom_jitter(data=g1rev.mcore.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + theme_void() + ggtitle("g1rev") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

#no significant g1rev hits for metacore so this line was extracted
#geom_jitter(data=g1rev.mcore.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1)

hpm3AvC.mcore.filt <- hpm3AvC.metacore %>% filter(FDR <= 0.05)     
hpm3AvC.mcore.filt <- tibble::rownames_to_column(hpm3AvC.mcore.filt,"Name")
ac.mcore.nohit <- hpm3AvC.mcore.filt %>% filter(Hit == "Other")
ac.mcore.hit <- hpm3AvC.mcore.filt %>% filter(Hit == "Hit")
ac.mcore.plot <- ggplot() + geom_jitter(data=ac.mcore.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.5, size=0.6, width=0.1) + geom_jitter(data=ac.mcore.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("hpm3.AvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip() 

MuscleSvC.mcore.filt <- MuscleSvC.metacore %>% filter(FDR <= 0.05)     
MuscleSvC.mcore.filt <- tibble::rownames_to_column(MuscleSvC.mcore.filt,"Name")
sc.mcore.nohit <- MuscleSvC.mcore.filt %>% filter(Hit == "Other")
sc.mcore.hit <- MuscleSvC.mcore.filt %>% filter(Hit == "Hit")
sc.mcore.plot <- ggplot() + geom_jitter(data=sc.mcore.nohit, aes(x="Collection",y=FDR), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=sc.mcore.hit, aes(x="Collection",y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("MuscleSvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()

ggarrange(ec.mcore.plot,g1rev.mcore.plot,ac.mcore.plot,sc.mcore.plot, legend = FALSE, ncol=4, nrow=1)
```

*Import IPA Data*
```{r}
EvC.ipa <- read.xlsx("../shared_data/EvC_ipa_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
G1vRev.ipa <- read.xlsx("../shared_data/G1vRev_ipa_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
hpm3AvC.ipa <- read.xlsx("../shared_data/hpm3_AvC_ipa_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
MuscleSvC.ipa <- read.xlsx("../shared_data/Muscle_SkeletalvsCardiac_ipa_withOverlaps.xlsx", colNames=TRUE, rowNames=TRUE)
```

*IPA Summary Plots_v2*

```{r, fig.width=10, fig.height=3}
evc.ipa.filt <- EvC.ipa %>% filter(p_value <= 0.05)          
evc.ipa.filt <- tibble::rownames_to_column(evc.ipa.filt,"Name")
evc.ipa.nohit <- evc.ipa.filt %>% filter(Hit == "Other")  
evc.ipa.hit <- evc.ipa.filt %>% filter(Hit == "Hit")  
ec.ipa.plot <- ggplot() + geom_jitter(data=evc.ipa.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=evc.ipa.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("EvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()              

g1vrev.ipa.filt <- G1vRev.ipa %>% filter(p_value <= 0.05)          
g1vrev.ipa.filt <- tibble::rownames_to_column(g1vrev.ipa.filt,"Name")
g1rev.ipa.nohit <- g1vrev.ipa.filt %>% filter(Hit == "Other")  
g1rev.ipa.hit <- g1vrev.ipa.filt %>% filter(Hit == "Hit")  
g1rev.ipa.plot <- ggplot() + geom_jitter(data=g1rev.ipa.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=g1rev.ipa.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("g1rev") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()              

hpm3AvC.ipa.filt <- hpm3AvC.ipa %>% filter(p_value <= 0.05)          
hpm3AvC.ipa.filt <- tibble::rownames_to_column(hpm3AvC.ipa.filt,"Name")
ac.ipa.nohit <- hpm3AvC.ipa.filt %>% filter(Hit == "Other")  
ac.ipa.hit <- hpm3AvC.ipa.filt %>% filter(Hit == "Hit")  
ac.ipa.plot <- ggplot() + geom_jitter(data=ac.ipa.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.5, size=0.6, width=0.1) + geom_jitter(data=ac.ipa.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("hpm3.AvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()              


MuscleSvC.ipa.filt <- MuscleSvC.ipa %>% filter(p_value <= 0.05)          
MuscleSvC.ipa.filt <- tibble::rownames_to_column(MuscleSvC.ipa.filt,"Name")
sc.ipa.nohit <- MuscleSvC.ipa.filt %>% filter(Hit == "Other")  
sc.ipa.hit <- MuscleSvC.ipa.filt %>% filter(Hit == "Hit")  
sc.ipa.plot <- ggplot() + geom_jitter(data=sc.ipa.nohit, aes(x="Collection",y=p_value), color="black", alpha=0.4, size=0.6, width=0.1) + geom_jitter(data=sc.ipa.hit, aes(x="Collection",y=p_value), color="red", alpha=1, size=2, width=0.1) + theme_void() + ggtitle("MuscleSvC") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_rect(color = "black", size=1)) + coord_flip()              

ggarrange(ec.ipa.plot,g1rev.ipa.plot,ac.ipa.plot,sc.ipa.plot, legend = FALSE, ncol=4, nrow=1)        
```

*Import iPathway Data*
*iPathway Summary Plots*

*Plotting the full EvC GSEA results*

```{r, fig.width=12, fig.height=6}
pvals <- EvC.GSEA  %>% filter(Collection %in% c("h","c2cgp","c2cp","c5bp", "c5mf", "c5cc"))
pvals <- tibble::rownames_to_column(pvals,"Term")
pvals.nohit <- pvals %>% filter(Hit == "Other")
pvals.hit <- pvals %>% filter(Hit == "Hit")

ggplot() + geom_jitter(data=pvals.nohit, aes(x=Collection,y=FDR), color="black", alpha=0.3, size=0.6, width=0.1) + geom_jitter(data=pvals.hit, aes(x=Collection,y=FDR), color="red", alpha=1, size=2, width=0.1) + theme_bw() + coord_flip()
```
*Summary Tables*

```{r}
table(EvC.GSEA$Collection,EvC.GSEA$Hit)
table(evc.gsea.filt$Collection,evc.gsea.filt$Hit)
```
## write session info*

```{r}
sessionInfo()
writeLines(capture.output(sessionInfo()), "sessionInfo.txt")
```